/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiseasesIndexRouteImport } from './routes/diseases.index'
import { Route as DiseasesSlugRouteImport } from './routes/diseases.$slug'
import { Route as DiseasesCategoryCategoryRouteImport } from './routes/diseases.category.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesIndexRoute = DiseasesIndexRouteImport.update({
  id: '/diseases/',
  path: '/diseases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesSlugRoute = DiseasesSlugRouteImport.update({
  id: '/diseases/$slug',
  path: '/diseases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesCategoryCategoryRoute =
  DiseasesCategoryCategoryRouteImport.update({
    id: '/diseases/category/$category',
    path: '/diseases/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/diseases/': typeof DiseasesIndexRoute
  '/diseases/category/$category': typeof DiseasesCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/diseases': typeof DiseasesIndexRoute
  '/diseases/category/$category': typeof DiseasesCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/diseases/': typeof DiseasesIndexRoute
  '/diseases/category/$category': typeof DiseasesCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/diseases/$slug' | '/diseases/' | '/diseases/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diseases/$slug' | '/diseases' | '/diseases/category/$category'
  id:
    | '__root__'
    | '/'
    | '/diseases/$slug'
    | '/diseases/'
    | '/diseases/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiseasesSlugRoute: typeof DiseasesSlugRoute
  DiseasesIndexRoute: typeof DiseasesIndexRoute
  DiseasesCategoryCategoryRoute: typeof DiseasesCategoryCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/': {
      id: '/diseases/'
      path: '/diseases'
      fullPath: '/diseases/'
      preLoaderRoute: typeof DiseasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/$slug': {
      id: '/diseases/$slug'
      path: '/diseases/$slug'
      fullPath: '/diseases/$slug'
      preLoaderRoute: typeof DiseasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/category/$category': {
      id: '/diseases/category/$category'
      path: '/diseases/category/$category'
      fullPath: '/diseases/category/$category'
      preLoaderRoute: typeof DiseasesCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiseasesSlugRoute: DiseasesSlugRoute,
  DiseasesIndexRoute: DiseasesIndexRoute,
  DiseasesCategoryCategoryRoute: DiseasesCategoryCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
